<?php
//Up core file 
// ACF fields
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5fb519e832852',
        'title' => 'Website conversion and tracking tools',
        'fields' => array(
            array(
                'key' => 'field_exit_capture_title_tab',
                'label' => 'Exit Capture',
                'name' => 'exit_capture_title_tab',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5fb519f6bc125',
                'label' => 'Activate Exit Capture',
                'name' => 'activate_exit_capture',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5fb51a0abc126',
                'label' => 'Exit Capture Title',
                'name' => 'exit_capture_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5fb519f6bc125',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                
                'key' => 'field_5fb51a0fbc127',
                'label' => 'Exit Capture Content',
                'name' => 'exit_capture_content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5fb519f6bc125',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 1,
                'delay' => 0,
            ),
            array(
                'key' => 'field_5fb51a2abc129',
                'label' => 'Exit Capture Button',
                'name' => 'exit_capture_button',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5fb519f6bc125',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'field_5f75b04e969d7',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
            ),
            array(
                'key' => 'field_exit_capture_img',
                'label' => 'Exit Capture Image',
                'name' => 'exit_capture_img',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5fb519f6bc125',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_agressive_exit_capture',
                'label' => 'Activate Aggressive Mode?',
                'name' => 'aggressive_exit_capture',
                'type' => 'true_false',
                'instructions' => 'By default, the popup only shows to a visitor once per session / visit. Tick this if you want it to show on every page load. This can impact user experience, only tick this if necessary.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5fb519f6bc125',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_display_exit_capture_countdown',
                'label' => 'Display Countdown Timer?',
                'name' => 'display_exit_capture_countdown',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5fb519f6bc125',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_exit_capture_countdown',
                'label' => 'Exit Capture Countdown Date',
                'name' => 'exit_capture_countdown',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'display_format' => 'd/m/Y',
                'return_format' => 'Y-m-d',
                'first_day' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5fb519f6bc125',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_display_exit_capture_countdown',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array(
                'key' => 'field_slide_callout_tab',
                'label' => 'Slide Callout',
                'name' => 'slide_callout_tab',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_activate_slide_callout',
                'label' => 'Activate Slide Callout',
                'name' => 'activate_slide_callout',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_slide_callout_title',
                'label' => 'Slide Callout Title',
                'name' => 'slide_callout_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_activate_slide_callout',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_slide_callout_content_type',
                'label' => 'Slide Callout Content Type',
                'name' => 'slide_callout_content_type',
                'type' => 'select',
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_activate_slide_callout',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'choices' => array(
                    'content' => 'Content',
                    'list' => 'List',
                ),
                'ui' => 1,
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_slide_callout_long_content',
                'label' => 'Slide Callout Content',
                'name' => 'slide_callout_long_content',
                'type' => 'text',
                'instructions' => 'Max 250 characters',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_activate_slide_callout',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_slide_callout_content_type',
                            'operator' => '==',
                            'value' => 'content',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'maxlength' => '250',
            ),
            array(
                'key' => 'field_slide_callout_short_content',
                'label' => 'Slide Callout Content',
                'name' => 'slide_callout_short_content',
                'type' => 'text',
                'instructions' => 'Max 100 characters',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_activate_slide_callout',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_slide_callout_content_type',
                            'operator' => '==',
                            'value' => 'list',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'maxlength' => '100',
            ),
            array(
                'key' => 'field_slide_callout_list',
                'label' => 'Slide Callout List Items',
                'name' => 'slide_callout_list',
                'type' => 'repeater',
                'min' => 0,
                'max' => 5,
                'button_label' => 'Add List Item',
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_activate_slide_callout',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_slide_callout_content_type',
                            'operator' => '==',
                            'value' => 'list',
                        ),
                    ),
                ),
                'sub_fields' => array(
                    array (
                        'key' => 'field_slide_callout_list_item',
                        'label' => 'List Item',
                        'name' => 'title',
                        'type' => 'text',
                    ),
                ),
            ),
            array(
                'key' => 'field_slide_callout_button',
                'label' => 'Slide Callout Button',
                'name' => 'slide_callout_button',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_activate_slide_callout',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'field_5f75b04e969d7',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
            ),
            array(
                'key' => 'field_agressive_slide_callout',
                'label' => 'Activate Aggressive Mode?',
                'name' => 'aggressive_slide_callout',
                'type' => 'true_false',
                'instructions' => 'By default, the slide callout only shows to a visitor once per session / visit. Tick this if you want it to show on every page load. This can impact user experience, only tick this if necessary.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_activate_slide_callout',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_highlight_bar_tab',
                'label' => 'Highlight Bar',
                'name' => 'highlight_bar_tab',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_activate_highlight_bar',
                'label' => 'Activate Highlight Bar',
                'name' => 'activate_highlight_bar',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_highlight_bar_title',
                'label' => 'Hightlight Bar Title',
                'name' => 'highlight_bar_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_activate_highlight_bar',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_display_highlight_bar_countdown',
                'label' => 'Display Countdown Timer?',
                'name' => 'display_highlight_bar_countdown',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_activate_highlight_bar',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_highlight_bar_countdown',
                'label' => 'Hightlight Bar Countdown Date',
                'name' => 'highlight_bar_countdown',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'display_format' => 'd/m/Y',
                'return_format' => 'Y-m-d',
                'first_day' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_activate_highlight_bar',
                            'operator' => '==',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_display_highlight_bar_countdown',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array(
                'key' => 'field_highlight_bar_button',
                'label' => 'Highlight Bar Button',
                'name' => 'highlight_bar_button',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_activate_highlight_bar',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'clone' => array(
                    0 => 'field_5f75b04e969d7',
                ),
                'display' => 'group',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 1,
            ),
            array(
                'key' => 'field_agressive_highlight_bar',
                'label' => 'Activate Aggressive Mode?',
                'name' => 'aggressive_highlight_bar',
                'type' => 'true_false',
                'instructions' => 'By default, the highlight bar only shows to a visitor once per session / visit. Tick this if you want it to show on every page load. This can impact user experience, only tick this if necessary.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_activate_highlight_bar',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-site-options',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
            ),
        ),
        'menu_order' => 10,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;