name: build-deploy-site
on: push

env:
  STAGING_SFTP_URL:
  STAGING_SFTP_USER:
  STAGING_SFTP_PASS:
  PROD_SFTP_URL:
  PROD_SFTP_USER:
  PROD_SFTP_PASS:

jobs:

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build-site]
    steps:
      - uses: actions/checkout@v3
      - run: |
          which sftp || ( apt-get update -y && apt-get install sftp -y )
          echo "SFTP installed!"
          which sshpass || ( apt-get update -y && apt-get install sshpass -y )
          echo "sshpass installed!"
          export THEME_PATH=$(find . -type f -name 'gulpfile.js' -not \( -path */node_modules/* -prune \) -print -quit | sed 's/gulpfile.js//')
          cd $THEME_PATH && export THEME_NAME=${PWD##*/} && rm -rf acf-json && rm -rf node_modules && cd ..
          sshpass -p $STAGING_SFTP_PASS sftp -oStrictHostKeyChecking=no -v -P 2222 $STAGING_SFTP_USER@$STAGING_SFTP_URL:/wp-content/themes/ <<< $"mkdir "$THEME_NAME""
          sshpass -p $STAGING_SFTP_PASS sftp -oStrictHostKeyChecking=no -v -P 2222 $STAGING_SFTP_USER@$STAGING_SFTP_URL:/wp-content/themes/ <<< $"put -r "$THEME_NAME""
      
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    steps:
      - uses: actions/checkout@v3
      - run: |
          which sftp || ( apt-get update -y && apt-get install sftp -y )
          echo "SFTP installed!"
          which sshpass || ( apt-get update -y && apt-get install sshpass -y )
          echo "sshpass installed!"
          export THEME_PATH=$(find . -type f -name 'gulpfile.js' -not \( -path */node_modules/* -prune \) -print -quit | sed 's/gulpfile.js//')
          cd $THEME_PATH && export THEME_NAME=${PWD##*/} && rm -rf acf-json && rm -rf node_modules && cd ..
          sshpass -p $PROD_SFTP_PASS sftp -oStrictHostKeyChecking=no -v -P 2222 $PROD_SFTP_USER@$PROD_SFTP_URL:/wp-content/themes/ <<< $"mkdir "$THEME_NAME""
          sshpass -p $PROD_SFTP_PASS sftp -oStrictHostKeyChecking=no -v -P 2222 $PROD_SFTP_USER@$PROD_SFTP_URL:/wp-content/themes/ <<< $"put -r "$THEME_NAME""